version: '3'

services: 
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress
    container_name: nginx

  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb
    container_name: wordpress

  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: always
    container_name: mariadb
  
volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: ${HOME}/data/wp
  db:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: ${HOME}/data/db

networks:
  inception: